apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-forward-appset-kustomize
  namespace: gitops-team-1
spec:
  generators:
    - git:
        repoURL: https://github.com/suranc/spring-forward-gitops
        revision: kind
        files:
        - path: "appset-kustomize/cluster-config/**/spring-forward-config.json"
  template:
    metadata:
      name: '{{cluster.name}}-spring-forward'
      labels:
        harness.io/envRef: '{{harness.envId}}'
        harness.io/serviceRef: '{{harness.serviceId}}'
        harness.io/buildRef: '{{imageTag}}'
    spec:
      project: 99cd9b82
      source:
        path: 'kustomize/overlays/{{cluster.name}}'
        repoURL: https://github.com/suranc/spring-forward-harness-example
        targetRevision: kind
        kustomize:
          images:
          - "ghcr.io/suranc/spring-forward-harness-example=ghcr.io/suranc/spring-forward-harness-example:{{imageTag}}"
      destination:
        server: '{{destination.server}}'
        namespace: '{{destination.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - Replace=true
