apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-forward-appset-kustomize
  namespace: gitops-team-1
spec:
  generators:
    - git:
        repoURL: https://gitlab.harness.internal/root/spring-forward-gitops.git
        revision: main
        files:
        - path: "appset-kustomize/cluster-config/**/spring-forward-config.json"
  template:
    metadata:
      name: '{{cluster.name}}-spring-forward'
    spec:
      project: eb5628ea
      source:
        path: 'kustomize/overlays/{{cluster.name}}'
        repoURL: https://gitlab.harness.internal/root/spring-forward-harness-example.git
        targetRevision: master
      destination:
        server: '{{destination.server}}'
        namespace: '{{destination.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
